import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Modal } from '@/shared/components'
import { useState } from 'react'
import Image from "next/image";
import {Post} from '@/widgets/profile/post/ui/Post'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [isModalOpen, setIsModalOpen] = useState(false);

    const handleOpenChange = (open: boolean) => {
        setIsModalOpen(open);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Modal
                    title="Post"
                    trigger={
                        <Image
                            src="/sphere-with-trees_result.jpg"
                            alt="post"
                            width={200}
                            height={200}
                        />
                    }
                    open={isModalOpen}
                    onOpenChange={handleOpenChange}
                >
                    <div>
                        <Post />
                    </div>
                </Modal>
            </main>
        </>
    );
}